@startuml


interface "FHIR RESTful API" as api

component "FHIR Validation Service" as validator
note right
HAPI FHIR Plain Server
end note

component "NHS England Terminology Server" as onto
note right
Used for validating SNOMED Terminology
end note

component "Inbuilt Terminology Server" as internal
note right
**CommonCodeSystemsTerminologyService**

Pre loaded with FHIR Profiles, ValueSets
and CodeSystems from supplied FHIR Packages
end note

interface "FHIR RESTful API" as Facade
note right
**TerminologyServiceValidationSupport**

Facade which handles Onto Server
authentication
end note

interface "FHIR RESTful API" as AWSFacade
note right
**AWSValidationSupport**

Facade which handles Cognito
authentication
end note

component AWSFHIRWorks
note right
Repository of FHIR Questionnsaire's
end note


api -- validator
validator -- Facade
validator -- internal
validator -- AWSFacade
Facade -- onto
AWSFacade -- AWSFHIRWorks

@enduml
