@startuml

skinparam svgDimensionStyle false

interface "FHIR RESTful API" as api

component "FHIR Validation Service" as validator
note right
[[https://hapifhir.io/hapi-fhir/docs/server_plain/server_types.html HAPI FHIR Plain Server]]
end note

package "[[https://hapifhir.io/hapi-fhir/docs/validation/validation_support_modules.html ValidationSupportChain]]" as ValidationSupportChain {

component "CommonCodeSystemsTerminologyService" as internal
note right
Pre loaded with FHIR Profiles, ValueSets
and CodeSystems from supplied FHIR Packages
end note

component "TerminologyServiceValidationSupport" as Facade
note right
Handles NHSE Terminology Server
authentication
end note

component "AWSValidationSupport" as AWSFacade
note right
Handles AWS Cognito
authentication
end note

internal -d[hidden]- Facade
Facade -d[hidden]- AWSFacade

}

component "[[https://digital.nhs.uk/services/terminology-server NHS England Terminology Server]]" as onto
note right
Used for validating SNOMED Terminology
end note

component "[[https://github.com/aws-solutions/fhir-works-on-aws AWS FHIRWorks]]" as AWSFHIRWorks
note right
Repository of FHIR Questionnsaire's
end note


api --> validator : FHIR RESTful API \n [[https://hl7.org/fhir/R4/resource-operation-validate.html $validate]]



validator --> Facade
validator --> internal
validator --> AWSFacade

Facade --> onto : FHIR RESTful API \n [[https://hl7.org/fhir/R4/codesystem-operation-validate-code.html $validate-code]]
AWSFacade --> AWSFHIRWorks : FHIR RESTful API

@enduml
