@startuml


component "FHIR Tools Application" as tool

interface  "[[https://github.com/NHSDigital/IOPS-FHIR-Integration-Engine FHIR Integration Engine]]" as iAWSFHIRWorks
note right
Implements
[[https://build.fhir.org/ig/HL7/sdc/ FHIR Structured Data Capture]]
end note

component "Clinical Data Repository" as AWSFHIRWorks
note right
[[https://github.com/aws-solutions/fhir-works-on-aws AWS FHIRWorks]]"
end note

interface "[[#validation-serivce FHIR Validation Service]]" as iValidate
note right
Implements
[[https://hl7.org/fhir/R4/validation.html FHIR Validation]]
end note


tool --> iAWSFHIRWorks : FHIR RESTful API
tool --> iValidate : FHIR RESTful API

iAWSFHIRWorks --> AWSFHIRWorks : FHIR RESTful API


@enduml
