# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: nhs.england.validation
canonical: https://fhir.nhs.uk/England/validation
version: 0.0.1-current
name: NHS_England_Validation
title: "FHIR Validation (internal/skunkworks)"
description: Internal FHIR Validator used in conjunction with IG publication processes
releaseLabel: ci-build

status: draft
publisher:
  ## Find your domain contact on the https://www.ihe.net/ihe_domains page
  - name: NHS England
  - url: https://england.nhs.uk/
  - email: interoperabilityteam@nhs.net
contact:
  - name: NHS England
    telecom:
      - system: email
        value: interoperabilityteam@nhs.net
license:  CC-BY-4.0
fhirVersion: 4.0.1
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2024+

dependencies:
  fhir.r4.ukcore.stu2:
    version: 2.1.0
    uri: https://simplifier.net/guide/ukcoreversionhistory

FSHOnly: false
# see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
parameters:
  path-binary: input/binary
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  excludexml: 'false'
  excludejsn: 'false'
  excludettl: 'true'
  excludemap: 'true'
  excludeexample: 'false'
  generate:
    - xml
    - json


#resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true
instanceOptions:
  setMetaProfile: never

pages:
  index.md:
    title: Home
    generation: markdown


menu:
  Home: index.html


